{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<p>
{' <a href="%ezpublish_link">Exponential</a> Copyright &copy; 1998-2026 <a href="%ez_link">7x</a> and others.'|i18n( 'design/admin/page_copyright',, hash( '%ezpublish_link', 'https://exponential.earth', '%ez_link', 'https://se7enx.com' ) )}
</p>
