{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<p>
Powered by <span class="edition-info">Exponential</span>.<br />
<a href="https://exponential.earth">Exponential</a> Copyright &copy; 1998 - 2026 <a href="https://se7enx.com">7x</a> and others.
</p>
