{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*
<p>
Powered by <span class="edition-info">eZ Publish</span>.<br />
<a href="http://ez.no/ezpublish">eZ Publish</a> Copyright &copy; 1999-2014 <a href="http://ez.no">eZ Systems AS</a> and others.
</p>
*}

{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $startyear=1998
     $show_evaluation_share_link=false()}
<p>
{'Powered by <span class="edition-info">%edition</span>. For more information see <a href=%about_link>ezinfo/about</a>.'|i18n( 'design/admin/page_copyright',, hash( '%edition', fetch( 'setup', 'edition' ), '%about_link', "/ezinfo/about"|ezurl ) )}</p>
<p>
{'<a href="%ezpublish_link">Exponential</a> Copyright &copy; %startyear - %currentyear <a href="%ez_link">7x</a> and others.'|i18n( 'design/admin/page_copyright',, hash( '%ezpublish_link', 'https://se7enx.com/Exponential', '%ez_link', 'https://se7enx.com', '%startyear', $startyear, '%currentyear', currentdate()|datetime( 'custom', '%Y' ) ) )}
</p>
{if $show_evaluation_share_link}
<p>
{'<a href="%evaluate_link">Evaluate Exponential (From 7x)</a> - <a href="%share_link">Become a member of the Exponential Community, get support and contribute</a>.'|i18n( 'design/admin/page_copyright',, hash( '%evaluate_link', 'https://se7enx.com', '%share_link', concat( 'https://share.exponential.earth?utm_content=Exponential+Community+Project+', fetch( 'setup', 'version' ) , '&utm_source=Exponential+Community+Project+Dashboard&utm_medium=Exponential+Community+Project+Dashboard&utm_campaign=Exponential+Community+Project+Dashboard' ) ) )}
</p>
{/if}
